version: "3.1"
services:
  # APP*****************************************
  mydebt:
    build: ./
    image: mydebt
    network_mode: host
    container_name: mydebt
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - "/volume2/Apps/MyDebt/logs:/usr/app/logs"
    restart: unless-stopped