version: "3.1"
services:
  postgres:
    image: postgres:9.6-alpine
    container_name: postgres_for_my_apps
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=macos
      - POSTGRES_USER=webappuser
      - POSTGRES_DB=my_debt
    restart: unless-stopped