version: "3.1"
services:
  postgres:
    image: postgres:latest
    container_name: postgres_for_my_apps
    expose:
      - 5435
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=macos
      - POSTGRES_USER=webappuser
      - POSTGRES_DB=my_debt
    restart: unless-stopped
  # APP*****************************************
  mycenter:
    build: ./
    image: mydebt
    network_mode: host
    container_name: mydebt
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - "/var/services/homes/mira/Drive/Apps/MyDebt/logs:/usr/app/logs"
    depends_on:
      - postgres
    restart: unless-stopped