version: "3.1"
services:
  # APP*****************************************
  mydebt:
    build: ./
    image: mydebt
    network_mode: host
    container_name: mydebt
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - "/var/services/homes/mira/Drive/Apps/MyDebt/logs:/usr/app/logs"
    restart: unless-stopped