server.port=8081

# POSTGRES - matches docker-compose.dev.yml
spring.datasource.url=jdbc:postgresql://localhost:5435/my_debt
spring.datasource.username=webappuser
spring.datasource.password=macos

spring.jpa.properties.hibernate.default_schema=public

# Hibernate ddl auto (create, create-drop, update)
spring.jpa.hibernate.ddl-auto=update
